#  Created byMartin.cz
#  Copyright (c) Martin Strohalm. All rights reserved.

# define values
NONE = 'none'

DEG = 'deg'
RAD = 'rad'

LEFT = 'left'
RIGHT = 'right'
TOP = 'top'
BOTTOM = 'bottom'
CENTER = 'center'
MIDDLE = 'middle'
START = 'start'
END = 'end'

BEFORE = 'before'
AFTER = 'after'

EVENODD = 'evenodd'
WINDING = 'winding'

N = 'n'
NW = 'nw'
NE = 'ne'
S = 's'
SW = 'sw'
SE = 'se'
W = 'w'
E = 'e'
C = 'c'

HORIZONTAL = 'h'
VERTICAL = 'v'

INSIDE = 'inside'
OUTSIDE = 'outside'

NATURAL = 'natural'
FACEIN = 'facein'
FACEOUT = 'faceout'
FOLLOW = 'follow'

AUTO = 'auto'
CUSTOM = 'custom'

TRANS = 'trans'
SOLID = 'solid'
DOTTED = '.'
DASHED = '-'
DASHDOTTED = '-.'

BUTT = 'butt'
SQUARE = 'square'
BEVEL = 'bevel'
MITER = 'miter'
ROUND = 'round'

NORMAL = 'normal'
ITALIC = 'italic'
LIGHT = 'light'
BOLD = 'bold'
BLACK = 'black'
HEAVY = 'heavy'
SEMIBOLD = 'semibold'
MEDIUM = 'medium'
ULTRALIGHT = 'ultralight'
THIN = 'thin'

SERIF = 'serif'
SANS = 'sans'
MONO = 'mono'

DAYS = 'd'
HOURS = 'h'
MINUTES = 'm'
SECONDS = 's'
MSECONDS = 'ms'
USECONDS = 'us'
NSECONDS = 'ns'

EVT_PROPERTY_CHANGED = 'evt_prop_changed'
EVT_PEN_CHANGED = 'evt_pen_changed'
EVT_BRUSH_CHANGED = 'evt_brush_changed'
EVT_TEXT_CHANGED = 'evt_text_changed'
EVT_VIEW = 'evt_view'
EVT_SIZE = 'evt_size'
EVT_ZOOM = 'evt_zoom'
EVT_KEY = 'evt_key'
EVT_KEY_DOWN = 'evt_key_down'
EVT_KEY_UP = 'evt_key_up'
EVT_MOUSE = 'evt_mouse'
EVT_MOUSE_MOTION = 'evt_mouse_motion'
EVT_MOUSE_SCROLL = 'evt_mouse_scroll'
EVT_MOUSE_ENTER = 'evt_mouse_enter'
EVT_MOUSE_LEAVE = 'evt_mouse_leave'
EVT_LEFT_DOWN = 'evt_left_down'
EVT_LEFT_UP = 'evt_left_up'
EVT_LEFT_DCLICK = 'evt_left_dclick'
EVT_MIDDLE_DOWN = 'evt_middle_down'
EVT_MIDDLE_UP = 'evt_middle_up'
EVT_MIDDLE_DCLICK = 'evt_middle_dclick'
EVT_RIGHT_DOWN = 'evt_right_down'
EVT_RIGHT_UP = 'evt_right_up'
EVT_RIGHT_DCLICK = 'evt_right_dclick'
