#  Created byMartin.cz
#  Copyright (c) Martin Strohalm. All rights reserved.

# import modules
import ui
from ...enums import *


PYTHONISTA_LINE_CAP = {
    LINE_CAP.BUTT: ui.LINE_CAP_BUTT,
    LINE_CAP.SQUARE: ui.LINE_CAP_SQUARE,
    LINE_CAP.ROUND: ui.LINE_CAP_ROUND}

PYTHONISTA_LINE_JOIN = {
    LINE_JOIN.BEVEL: ui.LINE_JOIN_BEVEL,
    LINE_JOIN.MITER: ui.LINE_JOIN_MITER,
    LINE_JOIN.ROUND: ui.LINE_JOIN_ROUND}

PYTHONISTA_LINE_STYLE = {
    LINE_STYLE.CUSTOM: LINE_STYLE.CUSTOM,
    LINE_STYLE.SOLID: LINE_STYLE.SOLID,
    LINE_STYLE.DOTTED: DASH_VALUES.DOTTED,
    LINE_STYLE.DASHED: DASH_VALUES.DASHED,
    LINE_STYLE.DASHDOTTED: DASH_VALUES.DASHDOTTED}

PYTHONISTA_FILL_RULE = {
    FILL_RULE.EVENODD: True,
    FILL_RULE.WINDING: False}

PYTHONISTA_FONT_STYLE = {
    FONT_STYLE.NORMAL: FONT_STYLE.NORMAL,
    FONT_STYLE.ITALIC: FONT_STYLE.ITALIC}

PYTHONISTA_FONT_WEIGHT = {
    FONT_WEIGHT.NORMAL: FONT_WEIGHT.NORMAL,
    FONT_WEIGHT.LIGHT: FONT_WEIGHT.LIGHT,
    FONT_WEIGHT.BOLD: FONT_WEIGHT.BOLD,
    FONT_WEIGHT.BLACK: FONT_WEIGHT.BLACK,
    FONT_WEIGHT.HEAVY: FONT_WEIGHT.HEAVY,
    FONT_WEIGHT.SEMIBOLD: FONT_WEIGHT.SEMIBOLD,
    FONT_WEIGHT.MEDIUM: FONT_WEIGHT.MEDIUM,
    FONT_WEIGHT.ULTRALIGHT: FONT_WEIGHT.ULTRALIGHT,
    FONT_WEIGHT.THIN: FONT_WEIGHT.THIN}

PYTHONISTA_FONT_FAMILY = {
    FONT_FAMILY.SERIF: FONT_FACE_SERIF,
    FONT_FAMILY.SANS: FONT_FACE_SANS,
    FONT_FAMILY.MONO: FONT_FACE_MONO}
