# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: ruff
on:
  push:
  #  branches:
  #    - master
  pull_request:
    branches:
      - master
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user ruff
    # exit-zero on select=ALL
    - run: ruff --exit-zero --format=github --select=ALL --target-version=py37 .
    # exit-zero on select=ALL that are fixable
    - run: ruff --exit-zero --format=github --select=ALL --target-version=py37 . | grep "\[\*\]" || true
    # Just the showstopper issues
    - run: ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    # The default issues
    - run: ruff --format=github --target-version=py37 .
